"""Run a split-screen session: one nested sway window hosting N game instances.

Why nested sway: it is a real Wayland compositor (with XWayland) that shows
up on the host as ONE window, so the whole split-screen is a single surface
you can fullscreen, record or move. Any Wayland or X11 game runs unmodified
inside it, and we place windows by PID lineage rather than by title/class,
so no per-game handler is needed.

    python3 -m splitscreen.session examples/grid4.json
"""
from __future__ import annotations

import argparse
import os
import select
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
from types import SimpleNamespace
import time
from pathlib import Path

import i3ipc

from . import layout as layout_mod
from .assign import assign_slot
from .config import Instance, Session, load
from .procmatch import find_instance
from .sandbox import bwrap_argv

SETTLE_POLL_S = 0.25
KBD2PAD_TIMEOUT_S = 5.0
SETTLE_ROUNDS = 20  # keep re-asserting geometry for ~5 s after a window appears

NESTED_CONFIG = """\
# generated by splitscreen.session
default_border none
default_floating_border none
focus_follows_mouse no
xwayland enable
for_window [all] floating enable, border none
bindsym Mod4+Shift+q exit
"""


def wait_for(path: str, timeout: float) -> bool:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if os.path.exists(path):
            return True
        time.sleep(0.05)
    return False


def start_nested_sway(workdir: Path, width: int | None, height: int | None) -> tuple[subprocess.Popen, i3ipc.Connection, dict[str, str]]:
    cfg = workdir / "sway.conf"
    envfile = workdir / "env"
    text = NESTED_CONFIG
    if width and height:
        text += f"output * resolution {width}x{height}\n"
    text += f"exec sh -c 'echo \"$WAYLAND_DISPLAY $DISPLAY\" > {envfile}'\n"
    cfg.write_text(text)

    sock = str(workdir / "sway.sock")
    env = {**os.environ, "WLR_BACKENDS": "wayland", "SWAYSOCK": sock}
    with open(workdir / "sway.log", "wb") as log:  # child keeps its dup; parent does not need the handle
        proc = subprocess.Popen(["sway", "--unsupported-gpu", "-c", str(cfg)], env=env, stdout=log, stderr=log)
    if not wait_for(sock, 5.0) or not wait_for(str(envfile), 5.0):
        terminate_all([proc])
        raise RuntimeError(f"nested sway did not come up; see {workdir / 'sway.log'}")
    time.sleep(0.2)
    wl, x = (envfile.read_text().split() + [""])[:2]
    conn = i3ipc.Connection(socket_path=sock)
    return proc, conn, {"WAYLAND_DISPLAY": wl, "DISPLAY": x}


def _signal_tree(p: subprocess.Popen, sig: int) -> None:
    """Signal the process group when we created one (instances), else just the process."""
    try:
        if os.getpgid(p.pid) == p.pid:
            os.killpg(p.pid, sig)
        else:
            p.send_signal(sig)
    except ProcessLookupError:
        pass


def terminate_all(procs: list[subprocess.Popen], grace: float = 3.0) -> None:
    """SIGTERM, wait up to `grace`, then SIGKILL. Instances are launched in their own
    process group so gamescope, its reaper, bwrap and the game all go together."""
    for p in procs:
        if p.poll() is None:
            _signal_tree(p, signal.SIGTERM)
    deadline = time.monotonic() + grace
    for p in procs:
        while p.poll() is None and time.monotonic() < deadline:
            time.sleep(0.05)
        if p.poll() is None:
            _signal_tree(p, signal.SIGKILL)
            p.wait()
        else:
            _signal_tree(p, signal.SIGKILL)  # leader exited first: sweep any leftovers in its group


def pick_output(outputs) -> tuple[int, int] | None:
    """Pure: size of the first usable output, or None when the frame has no output
    (which is what the host closing our window looks like from inside)."""
    for o in outputs:
        if o.active and o.rect.width > 0 and o.rect.height > 0:
            return o.rect.width, o.rect.height
    return None


def output_size(conn: i3ipc.Connection, timeout: float = 5.0) -> tuple[int, int]:
    deadline = time.monotonic() + timeout
    while True:
        size = pick_output(conn.get_outputs())
        if size:
            return size
        if time.monotonic() > deadline:
            raise RuntimeError("nested sway reported no active output")
        time.sleep(0.1)


def instance_argv(inst: Instance, slot: layout_mod.Rect, pad_device: str | None) -> tuple[str, ...]:
    cmd: tuple[str, ...] = inst.command
    if inst.isolate_input:
        devices = tuple(inst.devices) + ((pad_device,) if pad_device else ())
        cmd = bwrap_argv(cmd, devices, inst.binds)
    if inst.gamescope:
        cmd = ("gamescope", "-W", str(slot.w), "-H", str(slot.h), "-w", str(slot.w), "-h", str(slot.h),
               "-b", "--force-windows-fullscreen", "--", *cmd)
    return cmd


def start_kbd2pad(inst: Instance, workdir: Path) -> tuple[subprocess.Popen | None, str | None]:
    if not inst.keyboard_to_pad:
        return None, None
    logpath = workdir / f"kbd2pad-{inst.id}.log"
    with open(logpath, "wb") as log:
        proc = subprocess.Popen(
            [sys.executable, "-m", "splitscreen.kbd2pad", "--device", inst.keyboard_to_pad, "--name", f"Split Pad {inst.id}"],
            stdout=subprocess.PIPE, stderr=log, text=True,
        )
    assert proc.stdout is not None
    line = ""
    if select.select([proc.stdout], [], [], KBD2PAD_TIMEOUT_S)[0]:
        line = proc.stdout.readline().strip()
    if not line.startswith("/dev/input/"):
        terminate_all([proc])
        raise RuntimeError(f"kbd2pad for {inst.id} failed or timed out; see {logpath}")
    return proc, line


def run_pre_launch(inst: Instance, workdir: Path) -> None:
    """Run the instance's pre_launch commands in order; any failure aborts the session."""
    for argv in inst.pre_launch:
        env = {**os.environ, **dict(inst.env), "SPLITSCREEN_INSTANCE": inst.id}
        with open(workdir / f"{inst.id}.log", "ab") as log:
            log.write(f"[split] pre_launch: {' '.join(argv)}\n".encode())
            rc = subprocess.run(argv, env=env, cwd=inst.cwd, stdout=log, stderr=log).returncode
        if rc != 0:
            raise RuntimeError(f"{inst.id}: pre_launch failed (exit {rc}): {' '.join(argv)}; see {workdir / f'{inst.id}.log'}")


def place(conn: i3ipc.Connection, con_id: int, slot: layout_mod.Rect) -> None:
    replies = conn.command(f"[con_id={con_id}] floating enable, border none, "
                           f"resize set {slot.w} px {slot.h} px, move position {slot.x} px {slot.y} px")
    for r in replies:
        if not r.success:
            print(f"[split] place failed for con {con_id}: {r.error}", flush=True)


def matches(con, slot: layout_mod.Rect) -> bool:
    r = con.rect
    return (r.x, r.y, r.width, r.height) == (slot.x, slot.y, slot.w, slot.h)


def float_host_window(nested_pid: int, width: int | None, height: int | None) -> None:
    """Best effort: if the host is sway, make our frame a floating window of the requested size."""
    host_sock = os.environ.get("SWAYSOCK")
    if not host_sock or not width or not height:
        return
    try:
        host = i3ipc.Connection(socket_path=host_sock)
        host.command(f"[pid={nested_pid}] floating enable, border none, resize set {width} px {height} px, move position center")
    except Exception as exc:  # host is not sway/i3, or refuses: purely cosmetic
        print(f"[split] host float skipped: {exc}", flush=True)


class Runner:
    def __init__(self, session: Session, workdir: Path):
        self.session = session
        self.instances_by_id = {i.id: i for i in session.instances}
        self.slot_ids = tuple(w.id for i in session.instances for w in i.window_specs)
        self.workdir = workdir
        self.procs: dict[str, subprocess.Popen] = {}
        self.helpers: list[subprocess.Popen] = []
        self.roots: dict[int, str] = {}
        self.slots: dict[str, layout_mod.Rect] = {}
        self.placed: dict[int, str] = {}      # con id -> slot (window spec) id
        self.pending: dict[int, str] = {}     # con id -> instance id, waiting for a matching title
        self.retries: dict[int, int] = {}
        self.sway: subprocess.Popen | None = None
        self.conn: i3ipc.Connection | None = None
        self.settle_conn: i3ipc.Connection | None = None
        self.stop_settling = threading.Event()

    def launch_instances(self, nested_env: dict[str, str]) -> None:
        for inst in self.session.instances:
            slot = self.slots[inst.window_specs[0].id]  # gamescope sizes to the instance's first slot
            run_pre_launch(inst, self.workdir)
            helper, pad = start_kbd2pad(inst, self.workdir)
            if helper:
                self.helpers.append(helper)
            argv = instance_argv(inst, slot, pad)
            env = {**os.environ, **nested_env, **dict(inst.env), "SPLITSCREEN_INSTANCE": inst.id}
            with open(self.workdir / f"{inst.id}.log", "ab") as log:  # append: pre_launch output is already there
                proc = subprocess.Popen(argv, env=env, cwd=inst.cwd, stdout=log, stderr=log, start_new_session=True)
            self.procs[inst.id] = proc
            self.roots[proc.pid] = inst.id
            print(f"[split] {inst.id}: pid {proc.pid} slot {slot} :: {' '.join(argv)}", flush=True)

    def on_window(self, conn: i3ipc.Connection, ev) -> None:
        con = ev.container
        if con is None or not con.pid:
            return
        if con.id in self.placed:
            # Clients often commit their own initial size after our first placement; re-apply until it sticks.
            slot_id = self.placed[con.id]
            if not matches(con, self.slots[slot_id]):
                place(conn, con.id, self.slots[slot_id])
            return
        if ev.change == "close":
            self.pending = {k: v for k, v in self.pending.items() if k != con.id}
            return
        if ev.change == "new":
            inst_id = find_instance(con.pid, self.roots)
            if inst_id is None:
                print(f"[split] ignoring foreign window pid={con.pid} app_id={con.app_id}", flush=True)
                return
            self.pending = {**self.pending, con.id: inst_id}
        elif ev.change != "title" or con.id not in self.pending:
            return
        inst_id = self.pending[con.id]
        inst = self.instances_by_id[inst_id]
        slot_id = assign_slot(inst.window_specs, self.placed.values(), con.name, con.app_id, con.window_class)
        if slot_id is None:
            print(f"[split] {inst_id}: window {con.id} title={con.name!r} matches no free slot yet", flush=True)
            return
        self.pending = {k: v for k, v in self.pending.items() if k != con.id}
        self.placed = {**self.placed, con.id: slot_id}
        place(conn, con.id, self.slots[slot_id])
        print(f"[split] placed {slot_id} (con {con.id}, pid {con.pid}, title={con.name!r})", flush=True)

    def place_existing(self) -> None:
        """Place windows that were already mapped before the loop started.

        Belt to the subscription's braces. With one instance the launch loop
        returns in milliseconds and nothing can appear inside it; with several,
        the first game starts seconds before the last -- every instance after
        the first waits for the one before it -- so its window mapping early is
        not a corner case, it is what happens every time. That was the bug:
        player one sat in the middle of the frame, unplaced, while everyone
        else took their corner.
        """
        assert self.conn
        for con in self.conn.get_tree().descendants():
            if con.pid and con.id not in self.placed:
                self.on_window(self.conn, SimpleNamespace(container=con, change="new"))

    def settle_loop(self) -> None:
        """Floating clients commit their own initial size after our first placement
        (the compositor honours it), so keep re-asserting the slot geometry for a
        few seconds after each window appears. Runs on its own IPC connection."""
        assert self.settle_conn
        while not self.stop_settling.wait(SETTLE_POLL_S):
            try:
                tree = self.settle_conn.get_tree()
            except Exception:
                continue
            for con in tree.descendants():
                slot_id = self.placed.get(con.id)
                if slot_id is None or self.retries.get(con.id, 0) >= SETTLE_ROUNDS:
                    continue
                self.retries = {**self.retries, con.id: self.retries.get(con.id, 0) + 1}
                if not matches(con, self.slots[slot_id]):
                    place(self.settle_conn, con.id, self.slots[slot_id])

    def on_output(self, conn: i3ipc.Connection, ev) -> None:
        # The host closing the frame window removes the nested output. Nothing can
        # be shown any more, so stop cleanly instead of crashing in relayout().
        if pick_output(conn.get_outputs()) is None:
            print("[split] frame window closed by host; shutting down", flush=True)
            conn.main_quit()
            return
        self.relayout()

    def relayout(self) -> None:
        assert self.conn
        w, h = output_size(self.conn)
        rects = layout_mod.compute(self.session.layout, len(self.slot_ids), w, h, **self.session.layout_args)
        self.slots = dict(zip(self.slot_ids, rects))
        self.retries = {}  # geometry changed: let the settle loop re-assert every window again
        for con_id, slot_id in self.placed.items():
            place(self.conn, con_id, self.slots[slot_id])

    def run(self) -> int:
        self.sway, self.conn, nested_env = start_nested_sway(self.workdir, self.session.width, self.session.height)
        # From here on every failure must tear down sway, games and (keyboard-grabbing) helpers.
        try:
            print(f"[split] nested sway up: {nested_env}, socket {self.workdir / 'sway.sock'}", flush=True)
            float_host_window(self.sway.pid, self.session.width, self.session.height)
            self.relayout()
            # Subscribed before anything is launched. `on()` sends the
            # subscription immediately and sway queues events from that moment,
            # so a window that maps during the launch loop is still delivered
            # once main() runs — where before, it produced no event anybody was
            # listening for.
            self.conn.on("window", self.on_window)
            self.conn.on("output", self.on_output)
            self.launch_instances(nested_env)
            self.place_existing()
            self.settle_conn = i3ipc.Connection(socket_path=str(self.workdir / "sway.sock"))
            threading.Thread(target=self.settle_loop, daemon=True).start()
            for sig in (signal.SIGINT, signal.SIGTERM):
                signal.signal(sig, lambda *_: self.conn.main_quit())
            self.conn.main()
        finally:
            self.shutdown()
        return 0

    def shutdown(self) -> None:
        self.stop_settling.set()
        terminate_all([*self.procs.values(), *self.helpers])  # games first, then kbd2pad releases keyboards
        if self.sway:
            terminate_all([self.sway])


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("config", help="session JSON (see examples/)")
    ap.add_argument("--workdir", help="where to keep logs/sockets (default: temp dir)")
    args = ap.parse_args(argv)
    for tool in ("sway",):
        if shutil.which(tool) is None:
            print(f"missing required tool: {tool}", file=sys.stderr)
            return 2
    try:
        session = load(args.config)
    except (OSError, ValueError) as exc:
        print(f"bad config: {exc}", file=sys.stderr)
        return 2
    if any(i.gamescope for i in session.instances) and shutil.which("gamescope") is None:
        print("config uses gamescope but it is not in PATH", file=sys.stderr)
        return 2
    if any(i.isolate_input for i in session.instances) and shutil.which("bwrap") is None:
        print("config isolates input but bwrap is not in PATH", file=sys.stderr)
        return 2
    workdir = Path(args.workdir) if args.workdir else Path(tempfile.mkdtemp(prefix="splitscreen-"))
    workdir.mkdir(parents=True, exist_ok=True)
    return Runner(session, workdir).run()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
